#!/usr/bin/env ruby
LUCKY_ROOT = File.dirname(__FILE__)

require 'highline'
require_relative 'lib/core'


timethen = Time.at(read_current_seed)
timenow = Time.now

unless timethen.day != timenow.day
  abort '[LS] Lucky Sample already refreshed for today'
else
  if ((timenow.to_i / 60) - (timethen.to_i / 60)) < 24
    abort '[LS] 24 hours has not passed'
  else
    `bundle exec #{File.expand_path("lucky", File.dirname(__FILE__))}`
  end
end
